name: verify
on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        # Only show new issues for a pull request.
        only-new-issues: true

  gomod:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: verify go.mod/go.sum
      run: |
        go mod tidy
        git diff --exit-code
